# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    $num_of_minions = 5

    config.vm.define "k8s-single-master" do |master|
        master.vm.box = "CentOS-7.HyperV.box"
        master.vm.hostname = "k8s.master"
        master.vm.network "public_network", bridge:"Default Switch"
        master.vm.provider "HyperV" do |h|
            h.cpus = 2
            h.memory = 1024
            h.maxmemory = 2024
            h.vmname = "k8s.master"
        end
        master.vm.provision "shell", path: "./scripts/config-sshd.sh", args:"172.17.40.169"
    end

    (1..$num_of_minions).each do |i|
        config.vm.define "k8s-single-minion#{i}" do |minion|
            minion.vm.box = "CentOS-7.HyperV.box"
            minion.vm.hostname = "k8s.minion.#{i}"
            minion.vm.network "public_network", bridge:"Default Switch"
            minion.vm.provider "HyperV" do |h|
                h.cpus = 1
                h.memory = 512
                h.maxmemory = 1024
                h.vmname = "k8s.minion.#{i}"
            end
            minion.vm.provision "shell", path: "./scripts/config-sshd.sh", args:"172.17.40.17#{i}"
        end
    end
end
